### ISSUE TITLE
XMPP - can't leave room

### ISSUE THREAD

**Issue by licaon-kter** [matrix-org/matrix-bifrost#53]
ejabberd log: https://gist.github.com/9d2601e0acefe836582aa73528f1d785

**Comment by Half-Shot** [comment]
I'm assuming this a gateway bug?

**Comment by jkasun** [comment]
Is this issue is a good first issue to get started?

**Comment by Half-Shot** [comment]
Errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrm probably not, it's likely to be complicate :(

**Comment by licaon-kter** [comment]
ejabberd blocking the whole bridge server:
```
s2s_access: s2s
acl:
  ...
  blocked_servers:
    server:
      - "bridge.xmpp.matrix.org"

access_rules:
  ...
  s2s:
    - deny: blocked_servers
    - allow
```

But my server log is full of:
```
[info] <0.5903.0>@ejabberd_s2s_in:handle_auth_success:181 (tls|<0.5903.0>) Accepted inbound s2s EXTERNAL authentication bridge.xmpp.matrix.org -> mydomain.tld (hidden_by_ejabberd)
[info] <0.5903.0>@ejabberd_s2s_in:process_closed:131 Closing inbound s2s connection bridge.xmpp.matrix.org -> mydomain.tld: Stream closed by local host: invalid-from
```

And my ghosts are stuck in the room:
![hotelbridgetonia](https://user-images.githubusercontent.com/2282799/54751073-776f8480-4be2-11e9-92d5-1b57f152b2db.jpg)

Fun stuff, the `[cnvrs]` user didn't even manage to actually join, more info here: https://github.com/conversejs/converse.js/issues/1459

@Half-Shot Plenty of commits in the mean time, some sound useful, they are not deployed yet?

**Comment by licaon-kter** [comment]
Still an issue with the restarted bridge.

**Comment by eeeeeta** [comment]
I also ran into this; I had to "solve" the problem with a swift
```
$ sudo iptables -I INPUT -p tcp -s 94.237.52.46 -j REJECT
```
(where that IP is `lethe.matrix.org`). While it works, this solution isn't ideal...

**Comment by ara4n** [comment]
irritating that the ejabberd log gist has been deleted.  i've just tried to repro this with Adium and can't; parting the room seems to part the user correctly, and the MUC doesn't continue to relay messages after having parted.

Anyone know what's the difference is between libpurple parting a MUC and conversations?

**Comment by licaon-kter** [comment]
@ara4n The gist disappearing must of been a cleaning mistake.

**Comment by Half-Shot** [comment]
I believe this is fixed in #144

**Comment by licaon-kter** [comment]
@Half-Shot do ping when that is actually deployed on the actual bridge, so we can test

**Comment by auscompgeek** [comment]
I just got myself stuck in Hotel California today. I understand that fix has been running on matrix.org for a while now.

**Comment by Half-Shot** [comment]
Yep, which room @auscompgeek ?

**Comment by bqv** [comment]
Apparently still an issue, reports from xmpp users of issues

**Comment by bqv** [comment]
@Half-Shot this needs to be fixed. I was on the fence before, but this is unusably frustrating...

**Comment by allnamesaretakeningithub** [comment]
I can confirm I cannot leave a matrix room

**Comment by bqv** [comment]
Forget it. Matrix/NewVector dont care about XMPP users. Remember that this is a corporate venture, and our experiences/opinions arent profitable. This will never be fixed.

**Comment by Admicos** [comment]
this is still a thing, and as a result i keep getting notifications and messages from places i quite like to not be in anymore.

is there any workaround that doesn't involve just rejecting matrix network packets? i have some other matrix groups i want to be in on

**Comment by mrusme** [comment]
Can't leave a room that hasn't been active anymore since August this year. I believe the room was either removed or something else happened, however, it's called `xfz (Discord) and 6339 others` now and when I try to leave it the Matrix desktop client tells me that...

```
myusername:matrix.org not in room !yhqiEdqNjyPbxtUjzm:matrix.org.
```

**Comment by allnamesaretakeningithub** [comment]
Since this bug is still affecting XMPP users I propose to change the name of the bridge to "Hotel California".

**Comment by haansn08** [comment]
Can confirm this issue exists. Adding the room JID to the blocklist seems to be the only solution for now. Also had delivery problems, in a sense that there was no indication if my message was actually sent to the room or not.

**Comment by maranda** [comment]
That is fixed and live on aria-net.org's Bifrost by way.

**Comment by allnamesaretakeningithub** [comment]
> That is fixed and live on aria-net.org's Bifrost by way.

@maranda and is there a merge request for this repo?

**Comment by maranda** [comment]
Waiting to know about the fate of another PR, before I open more

**Comment by bqv** [comment]
@Half-Shot take heed? Your work has been done for you :)

Unless of course @ara4n is instructing you to leave this broken... guess we'll find out!

**Comment by Neustradamus** [comment]
@Half-Shot, @ara4n: Have you taken a little time to look @maranda PR?
- https://github.com/matrix-org/matrix-bifrost/pull/289
